# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 21:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0001_initial'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fri_date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='matchmaking.Date'),
        ),
        migrations.AddField(
            model_name='user',
            name='mon_date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='matchmaking.Date'),
        ),
        migrations.AddField(
            model_name='user',
            name='sat_date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='matchmaking.Date'),
        ),
        migrations.AddField(
            model_name='user',
            name='sun_date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='matchmaking.Date'),
        ),
        migrations.AddField(
            model_name='user',
            name='thur_date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='matchmaking.Date'),
        ),
        migrations.AddField(
            model_name='user',
            name='tue_date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='matchmaking.Date'),
        ),
        migrations.AddField(
            model_name='user',
            name='wed_date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='matchmaking.Date'),
        ),
    ]
