# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170110_2142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='about_me',
            new_name='about',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='picture1',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='picture2',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='picture3',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='picture4',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='picture5',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='picture6',
            field=models.URLField(null=True),
        ),
    ]
