# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-31 21:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FCMDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_token', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='friday_end_time',
            new_name='fri_end_time',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='friday_start_time',
            new_name='fri_start_time',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='monday_end_time',
            new_name='mon_end_time',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='monday_start_time',
            new_name='mon_start_time',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='saturday_end_time',
            new_name='sat_end_time',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='saturday_start_time',
            new_name='sat_start_time',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='sunday_end_time',
            new_name='sun_end_time',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='sunday_start_time',
            new_name='sun_start_time',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='thursday_end_time',
            new_name='thur_end_time',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='thursday_start_time',
            new_name='thur_start_time',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='tuesday_end_time',
            new_name='tue_end_time',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='tuesday_start_time',
            new_name='tue_start_time',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='wednesday_end_time',
            new_name='wed_end_time',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='wednesday_start_time',
            new_name='wed_start_time',
        ),
        migrations.AddField(
            model_name='fcmdevice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
