# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170110_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='new_likes_notification',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='new_matches_notification',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='new_messages_notification',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='picture1_thumb',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='upcoming_dates_notification',
            field=models.BooleanField(default=True),
        ),
    ]
