# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-14 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170111_0556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='picture1_thumb',
            new_name='picture1_square_url',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='picture1',
            new_name='picture1_url',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='picture2',
            new_name='picture2_url',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='picture3',
            new_name='picture3_url',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='picture4',
            new_name='picture4_url',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='picture5',
            new_name='picture5_url',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='picture6',
            new_name='picture6_url',
        ),
        migrations.AddField(
            model_name='user',
            name='picture2_square_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='picture3_square_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='picture4_square_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='picture5_square_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='picture6_square_url',
            field=models.URLField(null=True),
        ),
    ]
