# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170114_2119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='picture1_url',
            new_name='picture1_portrait_url',
        ),
    ]
