# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-09 22:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20170209_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='likes_active',
            new_name='likes_fun',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='likes_culture',
            new_name='likes_museums',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='likes_nature',
            new_name='likes_parks',
        ),
    ]
