# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-17 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20170209_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
