# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 22:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0004_auto_20170117_1839'),
        ('api', '0007_auto_20170117_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedReports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_content', models.CharField(max_length=10000)),
                ('associated_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated_date', to='matchmaking.Date')),
                ('blocked_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_user', to=settings.AUTH_USER_MODEL)),
                ('blocking_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocking_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
