# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-01 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_user_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registration_city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='search_radius',
            field=models.IntegerField(default=10),
        ),
    ]
