# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-20 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_user_pass_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='num_times_liked',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='num_times_suggested',
            field=models.IntegerField(default=0),
        ),
    ]
