# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-20 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20170320_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='num_times_liked',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='num_times_suggested',
            field=models.FloatField(default=0),
        ),
    ]
