# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-18 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20170406_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcmdevice',
            name='operating_system',
            field=models.CharField(default='a', max_length=2),
            preserve_default=False,
        ),
    ]
