# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-16 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcmdevice',
            name='registration_token',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
