# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-16 16:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_user_email'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fcmdevice',
            unique_together=set([('registration_token', 'user', 'operating_system')]),
        ),
    ]
