# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-16 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20170516_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcmdevice',
            name='registration_token',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterUniqueTogether(
            name='fcmdevice',
            unique_together=set([('registration_token', 'user', 'operating_system')]),
        ),
    ]
