# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_expires_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('day', models.CharField(max_length=4)),
                ('start_time', models.TimeField()),
                ('user1_likes', models.CharField(default='u', max_length=1)),
                ('user2_likes', models.CharField(default='u', max_length=1)),
                ('place_id', models.CharField(max_length=300)),
                ('place_name', models.CharField(max_length=300)),
                ('category', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='YelpAccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
    ]
