# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='place_name',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
