# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 18:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0002_auto_20170120_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='MutualFriend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('picture', models.URLField()),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='matchmaking.Date')),
            ],
        ),
    ]
