# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 00:33
from __future__ import unicode_literals

from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0002_date_place_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='original_expires_at',
            field=models.DateTimeField(timezone.now()),
            preserve_default=False,
        ),
    ]
