# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0003_date_original_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='original_expires_at',
            field=models.DateTimeField(),
        ),
    ]
