# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 18:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0004_auto_20170126_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='date_of_date',
            field=models.DateField(default=datetime.datetime(2017, 1, 26, 18, 54, 15, 714237, tzinfo=utc)),
        ),
    ]
