# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-31 21:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0005_date_date_of_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='date_of_date',
            field=models.DateField(default=datetime.datetime(2017, 1, 31, 21, 17, 6, 281644, tzinfo=utc)),
        ),
    ]
