# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-07 16:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0006_auto_20170131_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='date_of_date',
            field=models.DateField(default=datetime.datetime(2017, 2, 7, 16, 23, 18, 259638, tzinfo=utc)),
        ),
    ]
