# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-09 15:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0007_auto_20170207_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='date_of_date',
            field=models.DateField(default=datetime.datetime(2017, 2, 9, 15, 30, 24, 551443, tzinfo=utc)),
        ),
    ]
