# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-09 22:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0009_auto_20170209_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='date_of_date',
            field=models.DateField(default=datetime.datetime(2017, 2, 9, 22, 53, 36, 856682, tzinfo=utc)),
        ),
    ]
