# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-17 19:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0010_auto_20170209_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='date_of_date',
            field=models.DateField(default=datetime.datetime(2017, 2, 17, 19, 40, 1, 184001, tzinfo=utc)),
        ),
    ]
