# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-21 19:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0011_auto_20170217_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='inspected_match',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='date',
            name='date_of_date',
            field=models.DateField(default=datetime.datetime(2017, 2, 21, 19, 1, 47, 858282, tzinfo=utc)),
        ),
    ]
