# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-01 19:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0013_auto_20170223_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='date_of_date',
            field=models.DateField(default=datetime.datetime(2017, 3, 1, 19, 11, 16, 395173, tzinfo=utc)),
        ),
    ]
