# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-09 17:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0014_auto_20170301_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='date_of_date',
            field=models.DateField(default=datetime.datetime(2017, 3, 9, 17, 45, 56, 13337, tzinfo=utc)),
        ),
    ]
