# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-16 16:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0015_auto_20170309_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='date_of_date',
            field=models.DateField(default=datetime.datetime(2017, 3, 16, 16, 34, 25, 536144, tzinfo=utc)),
        ),
    ]
