# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-20 22:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0016_auto_20170316_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='date_of_date',
            field=models.DateField(default=datetime.datetime(2017, 3, 20, 22, 57, 59, 398822, tzinfo=utc)),
        ),
    ]
