# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-06 14:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0019_auto_20170320_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='date_of_date',
            field=models.DateField(default=datetime.datetime(2017, 4, 6, 14, 24, 50, 388588, tzinfo=utc)),
        ),
    ]
