# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-17 15:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0021_auto_20170417_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='date_of_date',
            field=models.DateField(default=datetime.datetime(2017, 4, 17, 15, 54, 15, 55248, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='yelpbusinesshours',
            name='fri_end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='yelpbusinesshours',
            name='fri_start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='yelpbusinesshours',
            name='mon_end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='yelpbusinesshours',
            name='mon_start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='yelpbusinesshours',
            name='sat_end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='yelpbusinesshours',
            name='sat_start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='yelpbusinesshours',
            name='sun_end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='yelpbusinesshours',
            name='sun_start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='yelpbusinesshours',
            name='thur_end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='yelpbusinesshours',
            name='thur_start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='yelpbusinesshours',
            name='tue_end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='yelpbusinesshours',
            name='tue_start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='yelpbusinesshours',
            name='wed_end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='yelpbusinesshours',
            name='wed_start_time',
            field=models.TimeField(null=True),
        ),
    ]
