# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-17 17:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0022_auto_20170417_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yelpbusinesshours',
            name='id',
        ),
        migrations.AlterField(
            model_name='date',
            name='date_of_date',
            field=models.DateField(default=datetime.datetime(2017, 4, 17, 17, 4, 36, 172129, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='yelpbusinesshours',
            name='place_id',
            field=models.CharField(max_length=300, primary_key=True, serialize=False),
        ),
    ]
