# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-17 19:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0023_auto_20170417_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='YelpBusinessDetails',
            fields=[
                ('place_id', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('place_name', models.CharField(max_length=300)),
                ('mon_start_time', models.TimeField(null=True)),
                ('mon_end_time', models.TimeField(null=True)),
                ('tue_start_time', models.TimeField(null=True)),
                ('tue_end_time', models.TimeField(null=True)),
                ('wed_start_time', models.TimeField(null=True)),
                ('wed_end_time', models.TimeField(null=True)),
                ('thur_start_time', models.TimeField(null=True)),
                ('thur_end_time', models.TimeField(null=True)),
                ('fri_start_time', models.TimeField(null=True)),
                ('fri_end_time', models.TimeField(null=True)),
                ('sat_start_time', models.TimeField(null=True)),
                ('sat_end_time', models.TimeField(null=True)),
                ('sun_start_time', models.TimeField(null=True)),
                ('sun_end_time', models.TimeField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='YelpBusinessHours',
        ),
        migrations.RemoveField(
            model_name='date',
            name='place_name',
        ),
        migrations.AlterField(
            model_name='date',
            name='date_of_date',
            field=models.DateField(default=datetime.datetime(2017, 4, 17, 19, 42, 42, 835339, tzinfo=utc)),
        ),
    ]
