# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-16 16:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0027_auto_20170515_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='date_of_date',
            field=models.DateField(default=datetime.datetime(2017, 5, 16, 16, 51, 57, 273008, tzinfo=utc)),
        ),
    ]
