# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-16 16:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0029_auto_20170516_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='date_of_date',
            field=models.DateField(default=datetime.datetime(2017, 5, 16, 16, 56, 55, 435278, tzinfo=utc)),
        ),
    ]
