# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-30 20:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0030_auto_20170516_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='yelpbusinessdetails',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yelpbusinessdetails',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=13),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='date',
            name='date_of_date',
            field=models.DateField(default=datetime.datetime(2017, 5, 30, 20, 38, 14, 84767, tzinfo=utc)),
        ),
    ]
