# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-03 20:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0031_auto_20170530_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='distance_between_users',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='date',
            name='user1_distance_from_date_location',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='date',
            name='user1_latitude',
            field=models.DecimalField(decimal_places=6, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='date',
            name='user1_longitude',
            field=models.DecimalField(decimal_places=6, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='date',
            name='user2_distance_from_date_location',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='date',
            name='user2_latitude',
            field=models.DecimalField(decimal_places=6, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='date',
            name='user2_longitude',
            field=models.DecimalField(decimal_places=6, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='date',
            name='date_of_date',
            field=models.DateField(default=datetime.datetime(2017, 6, 3, 20, 3, 46, 168924, tzinfo=utc)),
        ),
    ]
