# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 03:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0002_date_place_name'),
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='matchmaking.Date'),
            preserve_default=False,
        ),
    ]
